spring.application.name=microservice-patient
server.port=8081

# Connexion MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/medilabo_patient}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:77:9R?h(Ndcgx8N-sY9M7E]/}

# Hibernate génère/complète le schéma automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
